name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"
          # 修改：添加了缓存依赖路径
          cache-dependency-path: gomobile/go.sum 
          check-latest: true

      # Set up JDK
      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "gradle"

      # 修改：移除了 with 代码块
      - name: Set up Android SDK + NDK
        uses: android-actions/setup-android@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Tun2Socks AAR
        run: ./gradlew :app:buildTun2SocksAar --stacktrace

      # Upload build aar to Artifacts ASAP
      - name: Upload build aar to Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: "tun2socks"
          path: app/libs/tun2socks.aar

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Build APKs (may fail independently from AAR)
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      # Upload APK artifact
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: oblivion-${{ github.sha }}-unsigned.apk
          path: |
            app/build/outputs/apk/release/*.apk
